import { CERT_DAYS_DEFAULT } from "../cert-days";
import type { AddOptions, Backend, CertOptions, PkiStatus, ServerStatus, VpnClient } from "../types";

/**
 * Fake backend for local development, screenshots and tests.
 * State lives in memory and resets when the process restarts.
 */

interface DemoClient {
  name: string;
  status: "active" | "revoked";
  certExpiry: string;
  /** Session start (epoch ms) or null when offline. */
  connectedSince: number | null;
  realIp: string | null;
  vpnIp: string | null;
  /** Bytes per second used to simulate traffic growth. */
  rate: number;
}

interface DemoState {
  startedAt: number;
  clients: readonly DemoClient[];
}

const DAY_MS = 86_400_000;
const HOUR_MS = 3_600_000;

function isoDate(epochMs: number): string {
  return new Date(epochMs).toISOString().slice(0, 10);
}

// Documentation-only address ranges (RFC 5737) so screenshots leak nothing.
function seedState(now: number): DemoState {
  const seed = (
    name: string,
    status: DemoClient["status"],
    expiresInDays: number,
    session: { ago: number; realIp: string; host: number; rate: number } | null,
  ): DemoClient => ({
    name,
    status,
    certExpiry: isoDate(now + expiresInDays * DAY_MS),
    connectedSince: session ? now - session.ago : null,
    realIp: session?.realIp ?? null,
    vpnIp: session ? `10.8.0.${session.host}` : null,
    rate: session?.rate ?? 0,
  });
  return {
    startedAt: now - 3 * DAY_MS - 4 * HOUR_MS,
    clients: [
      seed("server_a1b2c3d4", "active", 3600, null),
      seed("alice-laptop", "active", 3421, { ago: 5 * HOUR_MS, realIp: "203.0.113.24", host: 2, rate: 42_000 }),
      seed("bob-phone", "active", 3302, { ago: 47 * 60_000, realIp: "198.51.100.7", host: 3, rate: 9_500 }),
      seed("carol-desktop", "active", 2950, null),
      seed("ci-runner", "active", 364, { ago: 2 * DAY_MS, realIp: "192.0.2.150", host: 4, rate: 120_000 }),
      seed("dave-old", "revoked", 1200, null),
      seed("erin-tablet", "active", 12, null),
      seed("frank-home", "active", 3610, { ago: 12 * 60_000, realIp: "203.0.113.91", host: 5, rate: 3_200 }),
    ],
  };
}

const store = globalThis as unknown as { __demoState?: DemoState };

function getState(): DemoState {
  if (!store.__demoState) store.__demoState = seedState(Date.now());
  return store.__demoState;
}

function setState(next: DemoState): void {
  store.__demoState = next;
}

function sessionBytes(client: DemoClient, now: number): { bytesIn: number; bytesOut: number } {
  if (client.connectedSince === null) return { bytesIn: 0, bytesOut: 0 };
  const seconds = (now - client.connectedSince) / 1000;
  const bytesOut = Math.round(seconds * client.rate);
  return { bytesIn: Math.round(bytesOut * 0.18), bytesOut };
}

function toVpnClient(client: DemoClient, now: number): VpnClient {
  const expiry = Date.parse(`${client.certExpiry}T00:00:00Z`);
  return {
    name: client.name,
    status: client.status,
    certExpiry: client.certExpiry,
    daysRemaining: Math.floor((expiry - now) / DAY_MS),
    online: client.connectedSince !== null,
    realIp: client.realIp,
    vpnIp: client.vpnIp,
    connectedSince: client.connectedSince,
    ...sessionBytes(client, now),
  };
}

function fakeProfile(name: string): string {
  return [
    `# DEMO PROFILE for "${name}" - generated by openvpn-panel in demo mode.`,
    "# This file contains no real keys and will not connect anywhere.",
    "client",
    "proto udp",
    "remote vpn.example.com 1194",
    "dev tun",
    "resolv-retry infinite",
    "nobind",
    "persist-key",
    "persist-tun",
    "remote-cert-tls server",
    "verb 3",
    "<ca>",
    "-----BEGIN CERTIFICATE-----",
    "DEMO-ONLY-NOT-A-REAL-CERTIFICATE",
    "-----END CERTIFICATE-----",
    "</ca>",
    "",
  ].join("\n");
}

export class DemoBackend implements Backend {
  readonly kind = "demo";

  async getStatus(): Promise<ServerStatus> {
    const now = Date.now();
    const state = getState();
    const online = state.clients.filter((c) => c.connectedSince !== null);
    const uptimeSeconds = (now - state.startedAt) / 1000;
    // Historical traffic (all sessions since start) plus current sessions.
    const baseline = Math.round(uptimeSeconds * 55_000);
    const live = online.reduce(
      (acc, c) => {
        const b = sessionBytes(c, now);
        return { bytesIn: acc.bytesIn + b.bytesIn, bytesOut: acc.bytesOut + b.bytesOut };
      },
      { bytesIn: 0, bytesOut: 0 },
    );
    return {
      up: true,
      startedAt: state.startedAt,
      connectedCount: online.length,
      bytesIn: Math.round(baseline * 0.2) + live.bytesIn,
      bytesOut: baseline + live.bytesOut,
      version: "OpenVPN 2.6.14 (demo)",
      error: null,
    };
  }

  async listClients(): Promise<VpnClient[]> {
    const now = Date.now();
    return getState().clients.map((c) => toVpnClient(c, now));
  }

  async addClient(name: string, options: AddOptions = {}): Promise<string> {
    const state = getState();
    if (state.clients.some((c) => c.name === name)) {
      throw new Error(`Client "${name}" already exists`);
    }
    const client: DemoClient = {
      name,
      status: "active",
      certExpiry: isoDate(Date.now() + (options.certDays ?? CERT_DAYS_DEFAULT) * DAY_MS),
      connectedSince: null,
      realIp: null,
      vpnIp: null,
      rate: 0,
    };
    setState({ ...state, clients: [...state.clients, client] });
    return fakeProfile(name);
  }

  async revokeClient(name: string): Promise<void> {
    const state = getState();
    const target = state.clients.find((c) => c.name === name);
    if (!target) throw new Error(`Client "${name}" not found`);
    if (target.status === "revoked") throw new Error(`Client "${name}" is already revoked`);
    setState({
      ...state,
      clients: state.clients.map((c) =>
        c.name === name
          ? { ...c, status: "revoked", connectedSince: null, realIp: null, vpnIp: null, rate: 0 }
          : c,
      ),
    });
  }

  async renewClient(name: string, options: CertOptions = {}): Promise<string> {
    const state = getState();
    const target = state.clients.find((c) => c.name === name);
    if (!target || target.status === "revoked") throw new Error(`Client "${name}" cannot be renewed`);
    const certExpiry = isoDate(Date.now() + (options.certDays ?? CERT_DAYS_DEFAULT) * DAY_MS);
    setState({ ...state, clients: state.clients.map((c) => (c.name === name ? { ...c, certExpiry } : c)) });
    return fakeProfile(name);
  }

  /** The CRL is close to expiry so demo mode shows the warning. */
  async getPki(): Promise<PkiStatus> {
    const now = Date.now();
    return {
      serverCertExpiresAt: now + 3600 * DAY_MS,
      caCertExpiresAt: now + 3600 * DAY_MS,
      crlNextUpdate: now + 20 * DAY_MS,
    };
  }

  async disconnectClient(name: string): Promise<boolean> {
    const state = getState();
    const target = state.clients.find((c) => c.name === name);
    if (!target || target.connectedSince === null) return false;
    setState({
      ...state,
      clients: state.clients.map((c) =>
        c.name === name ? { ...c, connectedSince: null, realIp: null, vpnIp: null, rate: 0 } : c,
      ),
    });
    return true;
  }
}

/** Test hook: restore seed data. */
export function resetDemoState(now: number = Date.now()): void {
  setState(seedState(now));
}
